set timing on

spool create_big_indexes.out

  CREATE INDEX CEF_CNR.VEV_LAT_CLO_I ON CEF_CNR.VESSEL_EVENT (VES_ID, IS_LATEST, IS_CLOSED)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.VEV_VLO_ENTRY_FK_I ON CEF_CNR.VESSEL_EVENT (VLO_ENTRY_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.VEV_VLO_OUT_FK_I ON CEF_CNR.VESSEL_EVENT (VLO_OUT_ID)  
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.VEV_POLYGON_SEARCH_I ON CEF_CNR.VESSEL_EVENT (CZO_ID, VES_ID, ENTRY_TIME DESC, OUT_TIME DESC, IS_CLOSED, ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.VEV_PK_I ON CEF_CNR.VESSEL_EVENT (ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;

/*
 -- CAN NOT CREATE UNIQUE INDEX IN THIS SEQUENCE
remove the constraint prior to the index creation
*/
ALTER TABLE CEF_CNR.VESSEL_EVENT DROP CONSTRAINT VEV_UK1;

CREATE UNIQUE INDEX CEF_CNR.VEV_UK1_I ON CEF_CNR.VESSEL_EVENT ( VES_ID, ENTRY_TIME, CZO_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
-- 
ALTER TABLE CEF_CNR.VESSEL_EVENT ADD CONSTRAINT VEV_UK1 UNIQUE (VES_ID, ENTRY_TIME, CZO_ID) disable;

  CREATE INDEX CEF_CNR.VEV_TIME_SPAN_I ON CEF_CNR.VESSEL_EVENT (VES_ID, OUT_TIME, ENTRY_TIME)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.VLO_PK_I ON CEF_CNR.VESSEL_LOCATION (ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.VLO_LAT_I ON CEF_CNR.VESSEL_LOCATION (VES_ID, IS_LATEST)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.VLO_UK1_I ON CEF_CNR.VESSEL_LOCATION (AXSMARINE_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.VLO_UK2_I ON CEF_CNR.VESSEL_LOCATION (VES_ID, RECORD_TIME)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.VLO_DUD_I ON CEF_CNR.VESSEL_LOCATION (VES_ID, IS_DUD)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_ACCURACY_LEVEL_DIT_FK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (DIT_ACCURACY_LEVEL_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_CHANGE_TYPE_DIT_FK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (DIT_CHANGE_TYPE_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_DATSET_NAME_I ON CEF_CNR.HISTORICAL_CELL_VALUE (DATASET_NAME)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_LATEST_REVISION_HCV_FK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (HCV_LATEST_REVISION_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_PERIOD_UNIT_DIT_FK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (DIT_MINOR_PERIOD_UNIT_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_RCE_FK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (RCE_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_REVISION_REASON_DIT_FK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (DIT_REVISION_REASON_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_RLS_FK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (RLS_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.HCV_PK_I ON CEF_CNR.HISTORICAL_CELL_VALUE (ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.HCV_UK1_I ON CEF_CNR.HISTORICAL_CELL_VALUE (RCE_ID, RLS_ID, BEGIN_DATE, START_YEAR, END_YEAR, MINOR_PERIOD_START, MINOR_PERIOD_END, DIT_MINOR_PERIOD_UNIT_ID, REPORT_DATE)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_QUERY_I ON CEF_CNR.HISTORICAL_CELL_VALUE (RCE_ID, PERIOD_START, PERIOD_END)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_QUERY_RD_I ON CEF_CNR.HISTORICAL_CELL_VALUE (RCE_ID, REPORT_DATE)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.HCV_REPORT_DATE_I ON CEF_CNR.HISTORICAL_CELL_VALUE (REPORT_DATE)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.PTS_CPV_I ON CEF_CNR.PIERS_TRANSACTION (COMMODITY_ID, USPORT_ID, VDATE)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.PTS_PK_I ON CEF_CNR.PIERS_TRANSACTION (ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE UNIQUE INDEX CEF_CNR.PTS_UK_I ON CEF_CNR.PIERS_TRANSACTION (RECNUM)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.PTS_DPP_I ON CEF_CNR.PIERS_TRANSACTION (DIR, PDATE, POUNDS)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.PTS_PVE_I ON CEF_CNR.PIERS_TRANSACTION (VESSEL_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.PTS_IDX1 ON CEF_CNR.PIERS_TRANSACTION (COMMODITY_ID, VDATE, PDATE, POUNDS, DIR)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.PDE_DIT_MESSAGE_CATEGORY_FK_I ON CEF_CNR.PROCESSING_DETAIL (DIT_MESSAGE_CATEGORY_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;
  CREATE INDEX CEF_CNR.PDE_FPH_FK_I ON CEF_CNR.PROCESSING_DETAIL (FPH_ID)
TABLESPACE CEF_CNR_INDEX01  PARALLEL 8 ;


-- set indexes to noparallel
BEGIN
  FOR tmp IN (SELECT t.*,
                     'alter index ' || t.owner || '.' || t.index_name ||
                     ' noparallel' sql_str
                FROM (SELECT owner,
                             index_name,
                             owner || '_INDEX01' tablespace_name
                        FROM dba_indexes
                       WHERE owner IN
                             ('CEF_CNR', 'MPD2_CNR', 'STE_CNR', 'OIL_CNR',
                              'EMS_CNR', 'OTD_CNR', 'FRT_CNR', 'GFMS_CNR',
                              'CEF_APDS', 'MPD2_APDS', 'STE_APDS', 'OIL_APDS',
                              'EMS_APDS', 'OTD_APDS', 'FRT_APDS', 'GFMS_APDS',
                              'PLATTS', 'SDI_CNR', 'SPATIAL',
                              'NDA_CNR')
                         AND index_type NOT IN ('LOB', 'DOMAIN')
                         AND table_name IN
                             ('VESSEL_LOCATION', 'VESSEL_EVENT',
                              'PIERS_TRANSACTION', 'PROCESSING_DETAIL',
                              'HISTORICAL_CELL_VALUE')) t
              --WHERE rownum <= 1
              ) LOOP
    dbms_output.put_line(tmp.sql_str);
    EXECUTE IMMEDIATE tmp.sql_str;
  
  END LOOP;
END;
/

spool off
