grant SELECT on SYS.DBA_LOCK to MPD2_CNR;
grant SELECT on SYS.DBA_LOCK to MPD2_APDS;
grant EXECUTE on SYS.DBMS_CRYPTO to GFMS_CNR;
grant EXECUTE on SYS.DBMS_CRYPTO to EMS_CNR;
grant EXECUTE on SYS.DBMS_CRYPTO to OTD_CNR;
grant EXECUTE on SYS.DBMS_CRYPTO to FRT_CNR;
grant EXECUTE on SYS.DBMS_CRYPTO to OIL_CNR;
grant EXECUTE on SYS.DBMS_CRYPTO to STE_CNR;
grant EXECUTE on SYS.DBMS_CRYPTO to MPD2_CNR;
grant EXECUTE on SYS.DBMS_CRYPTO to CEF_CNR;
grant EXECUTE on SYS.DBMS_LOCK to CEF_APDS;
grant EXECUTE on MDSYS.SDO_3GL to MPD2_CNR;
grant EXECUTE on MDSYS.SDO_3GL to CEF_CNR;

