exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('CEF_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('MPD2_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('STE_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('OIL_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('EMS_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('OTD_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('FRT_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('GFMS_CNR');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('PLATTS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('SDI');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('SPATIAL');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('NDA_CNR');

exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('MPD2_APDS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('STE_APDS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('OIL_APDS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('EMS_APDS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('OTD_APDS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('FRT_APDS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('CEF_APDS');
exec DBMS_STATS.UNLOCK_SCHEMA_STATS ('GFMS_APDS');

--lock statistics of some tables
execute DBMS_STATS.LOCK_TABLE_STATS('MPD2_CNR','AGGREGATED_DATA_01');
execute DBMS_STATS.LOCK_TABLE_STATS('MPD2_CNR','AGGREGATED_DATA_02');